version: 0.2
env:
  shell: bash
phases:
  build:
    commands:
      - ls -l
      - chmod +x ./eks/mi-aplicacion/mi-aplicacion/Aws/Cloudformation/api/build.sh
      - ./eks/mi-aplicacion/mi-aplicacion/Aws/Cloudformation/api/build.sh