AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation ImmsExchange Pipeline"

Parameters:
  PipelineConnectionArn:
    Description: The connection arn linked with the repository
    Type: String
  RepositoryId:
    Description: The repository that codepipeline will use to pull changes
    Type: String
  RepositoryBranch:
    Description: The repository branch that codepipeline will use to pull changes
    Type: String
    AllowedValues:
      - dev
      - qa
      - master
      - main
    ConstraintDescription: must be a dev, qa, or master
  EnvironmentType:
    Description: The environment type
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: must be a dev, test or prod
  ApplicationName:
    Description: Application name used to navigate throug the app file structure
    Type: String
  S3Bucket:
    Description: S3 Bucket to store the artifacts generated during the pipeline
    Type: String
  CFRole:
    Description: Cloudformation role with permissions to create the required resources
    Type: String
  EKSClusterName:
    Description: EKS cluster name created in cloudformation
    Type: String
  # CodePipelineRoleArn:
  #   Description: CodePipelineRole
  #   Type: String
  # CodeBuildRoleArn:
  #   Description: CodeBuildRole Arn
  #   Type: String
  EksClusterRoleArn:
    Description: CodeDeployRole Arn
    Type: String

Resources:

  PipelineBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      VersioningConfiguration:
        Status: Enabled
  
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-CodeBuild
      ServiceRole: !Ref CFRole
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Sub ${AWS::StackName}-CodeBuildLogGroup
          Status: ENABLED
          StreamName: !Sub ${AWS::StackName}-CodeBuildLogStream
      Artifacts:
        Type: CODEPIPELINE
        Name: !Sub ${EnvironmentType}-miaplicacion-pipeline-artifacts
        EncryptionDisabled: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub "eks/mi-aplicacion/mi-aplicacion/Aws/CloudFormation/api/buildspec.yml" #BE SURE TO CHANGE THIS PATH SINCE MAPPED VALUES ARE NOT ALLOWED HERE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: S3Bucket
            Type: PLAINTEXT
            Value: !Ref S3Bucket
          - Name: ENVIRONMENT_TYPE
            Type: PLAINTEXT
            Value: !Ref EnvironmentType
          - Name: APPLICATION_NAME
            Type: PLAINTEXT
            Value: !Ref ApplicationName
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          - Name: AWS_CLUSTER_NAME
            Type: PLAINTEXT
            Value: !Ref EKSClusterName
          - Name: EKS_ROLE
            Type: PLAINTEXT
            Value: !Ref EksClusterRoleArn
          - Name: CLOUDFORMATION_ROLE
            Value: !Ref CFRole

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${ApplicationName}-pipeline-${EnvironmentType}
      RoleArn: !Ref CFRole
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineBucket
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Region: us-east-2
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ConnectionArn: !Ref PipelineConnectionArn
                FullRepositoryId: !Ref RepositoryId
                BranchName: !Ref RepositoryBranch
                OutputArtifactFormat: "CODE_ZIP"
        - Name: Deploy
          Actions:
            - Name: DeployToKubernetes
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Ref CodeBuild