AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation ImmsExchange Pipeline"

Parameters:
  PipelineConnectionArn:
    Description: The connection arn linked with the repository
    Type: String
  RepositoryId:
    Description: The repository that codepipeline will use to pull changes
    Type: String
  RepositoryBranch:
    Description: The repository branch that codepipeline will use to pull changes
    Type: String
    AllowedValues:
      - dev
      - qa
      - master
      - main
    ConstraintDescription: must be a dev, qa, or master
  EnvironmentType:
    Description: The environment type
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: must be a dev, test or prod
  ApplicationName:
    Description: Application name used to navigate throug the app file structure
    Type: String
  S3Bucket:
    Description: S3 Bucket to store the artifacts generated during the pipeline
    Type: String
  CFRole:
    Description: Cloudformation role with permissions to create the required resources
    Type: String
  EKSClusterName:
    Description: EKS cluster name created in cloudformation
    Type: String

Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
                - "codebuild.amazonaws.com"
                - "codedeploy.amazonaws.com"
                - "s3.amazonaws.com"
                - "kms.amazonaws.com"
                - "eks.amazonaws.com"
                - "ecr.amazonaws.com"
                - "ec2.amazonaws.com"
                - "iam.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /service-role/
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource: "arn:aws:secretsmanager:*:*:secret:build/*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "cloudformation:*"
                  - "kms:*"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:CompleteLayerUpload"
                  - "ecr:GetAuthorizationToken"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:PutImage"
                  - "ecr:UploadLayerPart"
                  - "eks:*"
                  - "s3:*"
                  - "codepipeline:*"
                  - "codebuild:*"
                  - "codedeploy:*"
                Resource:
                  - "*"
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/${ApplicationName}-eks-role-${EnvironmentType}
  CodePipeLineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
                - "codebuild.amazonaws.com"
                - "codedeploy.amazonaws.com"
                - "cloudformation.amazonaws.com"
                - "s3.amazonaws.com"
                - "kms.amazonaws.com"
                - "eks.amazonaws.com"
                - "ecr.amazonaws.com"
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: !Sub ${EnvironmentType}-miaplicacion-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "codestar-connections:*"
                  - "codebuild:*"
                  - "s3:*"
                  - "cloudformation:*"
                  - "cloudwatch:*"
                  - "iam:PassRole"
                  - "ecr:*"
                  - "eks:*"
                  - "ec2:*"
                Resource:
                  - "*"
  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeDeployRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeDeployPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - autoscaling:CompleteLifecycleAction
                  - autoscaling:DeleteLifecycleHook
                  - autoscaling:Describe*
                  - autoscaling:RecordLifecycleActionHeartbeat
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:GetObjectVersion
                  - s3:GetObjectAcl
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecs:RegisterTaskDefinition
                  - ecs:DeregisterTaskDefinition
                  - ecs:UpdateService
                  - ecs:DescribeServices
                  - ecs:ListServices
                  - ecs:CreateService
                  - ecs:DeleteService
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetAuthorizationToken
                  - ecr:GetRepositoryPolicy
                  - ecr:DescribeRepositories
                  - ecr:ListImages
                  - ecr:DescribeImages
                  - ecr:BatchGetImage
                Resource: '*'
              - Effect: Allow
                Action:
                  - codedeploy:CreateDeployment
                  - codedeploy:Get* 
                  - codedeploy:RegisterApplicationRevision
                  - codedeploy:BatchGet*
                Resource: '*'

  PipelineBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      VersioningConfiguration:
        Status: Enabled
  
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-CodeBuild
      ServiceRole: !GetAtt CodeBuildRole.Arn
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Sub ${AWS::StackName}-CodeBuildLogGroup
          Status: ENABLED
          StreamName: !Sub ${AWS::StackName}-CodeBuildLogStream
      Artifacts:
        Type: CODEPIPELINE
        Name: !Sub ${EnvironmentType}-miaplicacion-pipeline-artifacts
        EncryptionDisabled: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: "eks/mi-aplicacion/mi-aplicacion/Aws/CloudFormation/api/buildspec.yml" #BE SURE TO CHANGE THIS PATH
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: S3Bucket
            Type: PLAINTEXT
            Value: !Ref S3Bucket
          - Name: ENVIRONMENT_TYPE
            Type: PLAINTEXT
            Value: !Ref EnvironmentType
          - Name: APPLICATION_NAME
            Type: PLAINTEXT
            Value: !Ref ApplicationName
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          - Name: AWS_CLUSTER_NAME
            Type: PLAINTEXT
            Value: !Ref EKSClusterName

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub mi-aplicacion-pipeline-${EnvironmentType}
      RoleArn: !GetAtt CodePipeLineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineBucket
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Region: us-east-2
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ConnectionArn: !Ref PipelineConnectionArn
                FullRepositoryId: !Ref RepositoryId
                BranchName: !Ref RepositoryBranch
                OutputArtifactFormat: "CODE_ZIP"
        - Name: Deploy
          Actions:
            - Name: DeployToKubernetes
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Ref CodeBuild