version: 0.2
phases:
  pre-build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ${AWS::Region})
  build:
    commands:
      - mkdir -p cloudformationPackage dockerImage
      - aws cloudformation package --template-file mi-aplicacion/Cloudformation/api/template.yml --s3-bucket $S3Bucket --output-template-file packaged-template.yml
     # - cp ./packaged-template.yml ./cloudformationPackage
      - echo Building Docker image...
      - docker build -t miaplicacion -f Mi-Aplicacion/Dockerfile .
      - docker tag miaplicacion:latest ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/miaplicacion-ecr-repo:latest
     # - docker save -o miaplicacion.tar miaplicacion
     # - cp ./miaplicacion.tar ./dockerImage
  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/miaplicacion-ecr-repo:latest
artifacts:
  files:
    - packaged-template.yml
    #- miaplicacion.tar
    #- Dockerfile